### PR TITLE
Split Files (Thanks partly to @Jerry-py)

### LINKED ISSUE #45: Implement separate files
## Description

Im just gonna be implementing separate files myself without circular import

## The problem

everything is stuffed in __init__.py 

## Checklist

- [ ] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

### PR DESCRIPTION
**Pull request by nav-github01001**
## Description

Fixes #45 . Thank @Jerry-py for half contributions
## Checklist

- [ ] - All code changes have been tested, if any
- [ ] - The documentation has been updated accordingly for any code changes
- [x] - This PR fixes an already existing issue #45 
- [ ] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [ ] - This PR fixes a bug
- [x] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [ ] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)

### CODE REVIEW

**Comment by nav-github01001** [comment]
So far so good

**Comment by Jerry-py** [comment]
@nav-github01001 this is still a draft byw

**Comment by nav-github01001** [comment]
> @nav-github01001 this is still a draft btw

yessir

**Comment by Jerrydotpy** [comment]
I say if your trying to avoid circluar imports then just import the file:
```py
import a

a.A()
```

**Comment by Jerrydotpy** [comment]
Also rip this https://github.com/EpikCord/EpikCord.py/pull/99 I think their were circular imports or not

**Pull request closed without merging**
